# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/roba/perso/github/arty-designstart-cm0/ips/clock_manager/arty_mmcm/arty_mmcm.xci
# IP: The module: 'arty_mmcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/roba/perso/github/arty-designstart-cm0/ips/clock_manager/arty_mmcm/arty_mmcm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_mmcm'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/roba/perso/github/arty-designstart-cm0/ips/clock_manager/arty_mmcm/arty_mmcm.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/roba/perso/github/arty-designstart-cm0/ips/clock_manager/arty_mmcm/arty_mmcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/roba/perso/github/arty-designstart-cm0/ips/clock_manager/arty_mmcm/arty_mmcm.xci
# IP: The module: 'arty_mmcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/roba/perso/github/arty-designstart-cm0/ips/clock_manager/arty_mmcm/arty_mmcm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/roba/perso/github/arty-designstart-cm0/ips/clock_manager/arty_mmcm/arty_mmcm.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/roba/perso/github/arty-designstart-cm0/ips/clock_manager/arty_mmcm/arty_mmcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
