# Automatically generated by ../../common/scripts/libspec2cfg.py --tool yosys -v --process nangate45 --top ../.. ../../libraries/libspec.py 
# !!! Do not edit !!!

tech_lef = '../../libraries/imported/nangate45/lef/NangateOpenCellLibrary.tech.lef'
lef_files.append('../../libraries/imported/nangate45/lef/NangateOpenCellLibrary.macro.mod.lef')
lef_files.append('../../libraries/local/bytewrite_ram_32bits/lef/bytewrite_ram_32bits_metal.lef')
lef_files.append('../../libraries/local/stdiocell/lef/iocells_metal.lef')