# Automatically generated by ../../common/scripts/libspec2cfg.py --tool yosys -v --process nangate45 --top ../.. ../../libraries/libspec.py 
# !!! Do not edit !!!

set tech_lef ../../libraries/imported/nangate45/lef/NangateOpenCellLibrary.tech.lef
lappend lef_files ../../libraries/imported/nangate45/lef/NangateOpenCellLibrary.macro.mod.lef
lappend lef_files ../../libraries/local/bytewrite_ram_32bits/lef/bytewrite_ram_32bits_metal.lef
lappend lef_files ../../libraries/local/stdiocell/lef/iocells_metal.lef