# Automatically generated by ../../common/scripts/libspec2cfg.py --tool yosys -v --process nangate45 --top ../.. ../../libraries/libspec.py 
# !!! Do not edit !!!

lappend lib_files ../../libraries/imported/nangate45/lib/NangateOpenCellLibrary_typical.lib
lappend lib_files ../../libraries/local/stdiocell/lib/stdiocell.lib
lappend lib_files ../../libraries/local/bytewrite_ram_32bits/lib/bytewrite_ram_32bits.lib
set libmax_stdcells ../../libraries/imported/nangate45/lib/NangateOpenCellLibrary_typical.lib
set libmax_bytewrite_ram_32bits ../../libraries/local/bytewrite_ram_32bits/lib/bytewrite_ram_32bits.lib
set libmax_stdiocell ../../libraries/local/stdiocell/lib/stdiocell.lib
