# Automatically generated by ../../common/scripts/libspec2cfg.py --tool yosys -v --process nangate45 --top ../.. ../../libraries/libspec.py 
# !!! Do not edit !!!

lib_files.append(../../libraries/imported/nangate45/lib/NangateOpenCellLibrary_typical.lib)
lib_files.append(../../libraries/local/stdiocell/lib/stdiocell.lib)
lib_files.append(../../libraries/local/bytewrite_ram_32bits/lib/bytewrite_ram_32bits.lib)
